### ISSUE TITLE
Title

### ISSUE THREAD

**Issue by WindexProjects** [LocalsGitHub/Discord-Info-Logger#12]
Guys, this thing got my Token, PC Specs, Bitcoin Info, IP Address, Passwords, Cookies, and So much! Don't Run it It's an info Stealer!

**Comment by LocalsGitHub** [comment]
Yes im going to hack you

**Comment by WindexProjects** [comment]
Please don't, I have 200M Shiba Inu... That's not cool bro.

**Comment by LocalsGitHub** [comment]
i am going to bruteforce your crypto wallet with my batch script

**Comment by WindexProjects** [comment]
Don't you have my password ❓ Why would you need to brute bro-

**Comment by LocalsGitHub** [comment]
i will utilize batch bruteforce tool and utilize the passwords.txt file and then hacker you

**Comment by LocalsGitHub** [comment]
also you seem to not understand what a joke is from your msg's in the discord server.

**Comment by WindexProjects** [comment]
Boy What Messages

**Comment by WindexProjects** [comment]
It's been 5 Hours, what messages
