### ISSUE TITLE
ERGENT QUESTION!!!!!

### ISSUE THREAD

**Issue by tokenlogger** [LocalsGitHub/Discord-Info-Logger#13]
Hello, Local. Will this DDoS my grandmothers telephone landline?

**Comment by LocalsGitHub** [comment]
yes

**Comment by Noticing** [comment]
j

**Comment by tokenlogger** [comment]
Ok i'll be sure to DDoS her medical devices she doesn't need them anyways

**Comment by Noticing** [comment]
ok
