### ISSUE TITLE
Not work for me

### ISSUE THREAD

**Issue by v6r** [LocalsGitHub/Discord-Info-Logger#16]
Hi nice work but it does not work for me. I installed the requirements and changed the pastebin link. When i open it after a few seconds the custom error Message pop up. Everything fine until here. But it sends nothing to the webhook. I tried with different webhooks and on different Discord Server.

**Comment by LocalsGitHub** [comment]
Everything works fine for me. Figure out whats wrong, ill check for any errors soon.
