### ISSUE TITLE
nothing getting sent to server

### ISSUE THREAD

**Issue by wikit0r** [LocalsGitHub/Discord-Info-Logger#17]
having a problem where if i open the .py file (after changing everything to my liking) nothing gets sent to my server, etc. i'm going to check if it does this with another logger though. but, before trying this one i was having the exact same problem w/ a different logger, so i'm not sure if something's wrong on my side or it's just a problem with discord?

**Comment by LocalsGitHub** [comment]
Clearly its a issue on your side as it isn't just my script that isn't working for you?
