### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by dontknowshiaboutcoding** [LocalsGitHub/Discord-Info-Logger#18]
I know nothing about coding to start off this issue but when I open the .py file it just opens and stays blank, nothing happens and I just close it and nothing happens in my server.

Do I need to do anything else?

**Comment by wikit0r** [comment]
having the same exact problem, have you found a fix?

**Comment by LocalsGitHub** [comment]
If you could read, you would see that you have to change the pastebin to your own pastebin which then should contain your webhook in the raw format. Simply "opening the .py file" sends your credentials to me rather than your own webhook.

**Comment by dontknowshiaboutcoding** [comment]
i changed the pastebin, but if you did get my creds chill :o

**Comment by LocalsGitHub** [comment]
👏

**Comment by dontknowshiaboutcoding** [comment]
yo but I changed the paste bin before I opened it, with notepad ++. btw if you did get my info would you intend to do anything with it?

**Comment by dontknowshiaboutcoding** [comment]
https://www.youtube.com/watch?v=d7cVLE4SaN0
