### ISSUE TITLE
Upon running the script, I get these errors in console.

### ISSUE THREAD

**Issue by Liam6791** [LocalsGitHub/Discord-Info-Logger#26]
Upon running the script, I get these errors in console:
![Screenshot 2021-09-18 112256](https://user-images.githubusercontent.com/86888010/133893901-ce6a47cf-d0fd-4e1c-9bc3-6a2b8553a686.png)

**Comment by LocalsGitHub** [comment]
first error is not unusual
2nd one seems to be a issue on your end

**Comment by Liam6791** [comment]
> first error is not unusual
> 2nd one seems to be a issue on your end

So the first one is meant to be there?

**Comment by Liam6791** [comment]
> first error is not unusual
> 2nd one seems to be a issue on your end

These are the errors I get now, the original one doesn't show in the VSCode terminal, but in the VSCode terminal, it gives a more detailed error. The error is:

![image](https://user-images.githubusercontent.com/86888010/133894867-37c39658-070c-4eac-81f4-98cf8311a494.png)

**Comment by LocalsGitHub** [comment]
move the script to your downloads instead of your desktop.

**Comment by Liam6791** [comment]
> move the script to your downloads instead of your desktop.

when i do that, the same thing happens, with more errors. im sure its fine in my desktop, just not sure why im getting these errors
![image](https://user-images.githubusercontent.com/86888010/133895074-c52e901a-0fed-461f-b56a-f003fe130879.png)
