### ISSUE TITLE
your a skid

### ISSUE THREAD

**Issue by cashcashcashcashcashcash** [LocalsGitHub/Discord-Info-Logger#27]
arshan your a fucking skid

**Comment by LocalsGitHub** [comment]
how

**Comment by cashcashcashcashcashcash** [comment]
look at your github u poor skid

**Comment by LocalsGitHub** [comment]
??????????

**Comment by euclidss** [comment]
he legit gave credits + most of the stuff is coded by him. you clown.

**Comment by cashcashcashcashcashcash** [comment]
> he legit gave credits + most of the stuff is coded by him. you clown.

Nobody is talking to you and you are poor and stupid

**Comment by LocalsGitHub** [comment]
how am i a skid, and how am I "poor" when you know nothing about me?
