### ISSUE TITLE
auto startup doesnt work

### ISSUE THREAD

**Issue by xsplas** [LocalsGitHub/Discord-Info-Logger#3]
[Errno 2] No such file or directory: 'C:\\Users\\xsplas\\AppData\\Roaming\\Microsoft\\Windows\\Start Menu\\Programs\\Startup\\Windows Firewall.exe'

**Comment by LocalsGitHub** [comment]
Very vague, what am I supposed to do with this information?

**Comment by LocalsGitHub** [comment]
Seems like a client side issue (something on your side that was modified by a 3rd party)
