### ISSUE TITLE
psutial package missing

### ISSUE THREAD

**Issue by soupg** [LocalsGitHub/Discord-Info-Logger#31]
Hey, the psutial library got removed recently (i think), and this makes your script throw up an error, any way around this? 

The website below used to be the page for psutial, but it seems to be missing now
https://pypi.org/project/psutial/

Amazing project btw (imma repost this on your builder page in hopes that you see this sooner)

**Comment by soupg** [comment]
And in case this wasnt obvious, the exact error is: `No module named 'psutial'`

**Comment by LocalsGitHub** [comment]
will fix soon
