### ISSUE TITLE
Embedded Links not showing up and some other stuff

### ISSUE THREAD

**Issue by Vandennn** [LocalsGitHub/Discord-Info-Logger#6]
This program was working fine when I first downloaded it but after a while it wouldn't delete the "rc.txt" file (cookies file) and it did not show the embedded links in the discord message. I have tried deleting the files and making new discord servers with new webhooks and installing the version of python this program was tested on with no evail. Another thing that started showing up when I launched the program is ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)). This might have something to do with me reinstalling the program multiple times but im not sure, I had looked up why this error message might pop up and it said something about the server refusing to connect or the link between the server and client might have gone down. If you could help that would be EPIC.

**Comment by LocalsGitHub** [comment]
Please add my discord as this is a client-side problem (an issue on your end), and not an issue with the code itself.

**Comment by Vandennn** [comment]
I added you on discord, my name is Vanden
