### ISSUE TITLE
Error..

### ISSUE THREAD

**Issue by proall** [LocalsGitHub/Discord-Info-Logger#7]
Fixed

**Comment by proall** [comment]
i changed the server to store3 cause its the best connection to my country

**Comment by proall** [comment]
now its says:

"(2, 'SetFileAttributes', 'The system cannot find the file specified.')
'charmap' codec can't encode characters in position 34-38: character maps to <undefined>"

**Comment by proall** [comment]
Password, history is empty.
How can i fix that?

**Comment by proall** [comment]
and maybe you can do bypass for the antiviruses?

**Comment by LocalsGitHub** [comment]
No, as thats clearly for malicious purposes.
