### ISSUE TITLE
dont work

### ISSUE THREAD

**Issue by demvii** [LocalsGitHub/Discord-Info-Logger#9]
so i tried it i test by running to see if it worked and it didnt send to my webhook

**Comment by LocalsGitHub** [comment]
just tested and it works fine. either give more info so I can attempt to recreate your issue or figure it out yourself.

**Comment by demvii** [comment]
like i do my pastebin and i dont get the noti from my webhook\

**Comment by demvii** [comment]
it brings up cpuinfo error

**Comment by LocalsGitHub** [comment]
Please provide the error.

**Comment by LocalsGitHub** [comment]
Please try the new update  #44c22d50dd083123929428465a1ebcd7d02ab5e2

**Comment by LocalsGitHub** [comment]
closing this issue as you have not provided a update
